<a href="https://colab.research.google.com/github/kkaradag2/DeepLearning/blob/main/02_tensor_math_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

shape=(2,3);
rand_tensor = torch.rand(shape);
ones_tensor = torch.ones(shape);
zeros_tensor = torch.zeros(shape);

print(rand_tensor);
print(ones_tensor);
print(zeros_tensor);

tensor([[0.2626, 0.1977, 0.1239],
        [0.0035, 0.2176, 0.4696]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
tensor = torch.rand(2,3);

print("Tensorun şekli", tensor.shape);
print("Tensorun veri tipi", tensor.dtype);
print("Tensorun saklama tipi", tensor.device);
#

Tensorun şekli torch.Size([2, 3])
Tensorun veri tipi torch.float32
Tensorun saklama tipi cpu


In [9]:
tensor = torch.rand(4,4);
tensor[:,1] = 0;

print(tensor);

tensor([[0.0107, 0.0000, 0.5492, 0.3793],
        [0.6127, 0.0000, 0.8669, 0.6570],
        [0.4711, 0.0000, 0.6899, 0.6794],
        [0.1309, 0.0000, 0.4061, 0.7535]])


In [14]:
tensor_a = torch.tensor([[2,4],
                        [5,8]]);


tensor_b = torch.tensor([[3,6],
                        [7,9]]);
# tensotleri birbirine eklemek için cat kullanılır
# dim = 0 satırdan ekler
tensor_c = torch.cat((tensor_a, tensor_b), dim=0);

# dim=1 sutundan ekle
tensor_d = torch.cat((tensor_a, tensor_b), dim=1);

print(tensor_c);

print(tensor_d);

tensor([[2, 4],
        [5, 8],
        [3, 6],
        [7, 9]])
tensor([[2, 4, 3, 6],
        [5, 8, 7, 9]])


In [17]:
# birden fazla tensor de ekelenebilir
tensor_a = torch.rand(2,3);
tensor_b = torch.rand(2,3);
tensor_c = torch.rand(2,3);

# sutundan ekliyoruz, 4x3 matris oluyor
tensor_d= torch.cat((tensor_a, tensor_b, tensor_c), dim=0);

print(tensor_d);

tensor([[0.8783, 0.3026, 0.6385],
        [0.0626, 0.7167, 0.2344],
        [0.7202, 0.3146, 0.7707],
        [0.9100, 0.7976, 0.5501],
        [0.7525, 0.4008, 0.1309],
        [0.2632, 0.9639, 0.3923]])


# iki tensorun çarpımı

tensorleri birbirleri il eçarpman için torch.mul kullanılır

In [21]:
# tek boyutlu
tensor_a = torch.tensor([1,2,3,4,5]);
tensor_b = torch.tensor([4,5,6,7,9]);

tensor_c = tensor_a.mul(tensor_b);  # axb

print(tensor_a);
print(tensor_b);
print(tensor_c);



tensor([1, 2, 3, 4, 5])
tensor([4, 5, 6, 7, 9])
tensor([ 4, 10, 18, 28, 45])


In [22]:
# 2x2 çarpımı

a= torch.tensor([[1,2],
                [3,4]]);

b= torch.tensor([[4,5],
                [6,7]]);

c= torch.mul(a,b);

print(a);
print(b);
print(c);

tensor([[1, 2],
        [3, 4]])
tensor([[4, 5],
        [6, 7]])
tensor([[ 4, 10],
        [18, 28]])


**Farklı Boyutlarda Tensör Çarpımı**

**torch.mul** fonksiyonu eleman-eleman çarpma yapar.
Bu nedenle yalnızca aynı boyutlu veya broadcasting kurallarına uyan tensörlerde kullanılabilir.

Matematiksel olarak geçerli olan matris çarpımı, mul ile yapılamaz.

Bu tür durumlarda **@ **operatörü (**torch.matmul**) kullanılmalıdır.

**Matris Çarpımı Kuralı**

A : (m × n)

B : (n × k)

A @ B : (m × k)


In [31]:
A = torch.rand(5, 3)
B = torch.rand(3, 4)

C = torch.matmul(A, B)

print(C)
#

tensor([[0.3343, 0.7375, 0.8417, 0.3798],
        [0.4051, 0.7755, 0.8753, 0.4279],
        [0.5682, 0.8213, 0.9857, 0.3563],
        [0.3137, 1.0895, 1.2096, 0.6012],
        [0.6923, 0.9549, 0.9624, 0.7907]])


In [33]:
# Bir tensore bir sayı ekleme yönetemi

A = torch.tensor([[1,2,3,0],
                  [5,6,7,0]]);

A.add_(5);

print(A)
# Matrisdeki her elemana 5 ekledi.

tensor([[ 6,  7,  8,  5],
        [10, 11, 12,  5]])


In [36]:
# Bir tensoru NumPy dizisine çevirme

A = torch.ones(5);
print(A);

B = A.numpy();

print(B);

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [37]:
#Bir Numpy dizisini tensor e çevirme

A = np.ones(5);
print(A);

B = torch.from_numpy(A);

print(B);


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
